# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: development

# test:
#   <<: *default
#   database: test

# production:
#   <<: *default
#   database: production



# default: &default
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   adapter: postgresql
#   database: myapp_development

# test:
#   <<: *default
#   adapter: postgresql
#   database: myapp_test

# production:
#   <<: *default
#   adapter: postgresql
#   database: myapp_production



default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: myapp_development

test:
  <<: *default
  adapter: postgresql
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['RENDER_DATABASE_NAME'] %>
  username: <%= ENV['RENDER_DATABASE_USER'] %>
  password: <%= ENV['RENDER_DATABASE_PASSWORD'] %>
  host: <%= ENV['RENDER_DATABASE_HOST'] %>
  port: <%= ENV['RENDER_DATABASE_PORT'] %>
